CREATE TABLE IF NOT EXISTS bill_item (
pkid INTEGER PRIMARY KEY AUTOINCREMENT,
bill_index_pkid INTEGER NOT NULL,
item_id INTEGER NOT NULL,
qty INTEGER NOT NULL,
price DECIMAL NOT NULL,
gst_amount DECIMAL NOT NULL
);