CREATE TABLE IF NOT EXISTS item (
pkid INTEGER PRIMARY KEY AUTOINCREMENT,
item_code TEXT NOT NULL,
item_name TEXT NOT NULL,
ma_cost DECIMAL NOT NULL,
category_id INTEGER NOT NULL,
image BLOB
);